version: "3.8"

services: 
  mongo:
    container_name: compracerta-mongo
    env_file: ./.env.mongo
    expose: 
      - "${MONGO_PORT_EXPOSED}"
    volumes: 
      - "compracerta-volume:/data/db"
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    networks:
      - compracerta-network
    restart: unless-stopped
  
  