version: "3.8"

services: 
  redis:
    container_name: compracerta-redis
    env_file: ./.env.redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - "${REDIS_PORT}"
    volumes:
      - "compracerta-volume:/var/lib/redis"
    networks:
      - compracerta-network
      - compracerta-rabbit-network
    restart: unless-stopped
